### ISSUE TITLE
Sun trajectory doesn't match original game

### ISSUE THREAD

**Issue by Allofich** [afritz1/OpenTESArena#142] opened 2019-03-03 16:14 UTC
Right now the sun in OpenTESArena moves straight up and down when rising or setting. As you probably know, it moves diagonally in the original game.

![sunrise](https://user-images.githubusercontent.com/19624336/53697867-1f323780-3e19-11e9-8277-54721ba0b076.gif)
Sunrise (6:18 AM - 8:10 AM)

![sunset](https://user-images.githubusercontent.com/19624336/53697900-70422b80-3e19-11e9-8336-3f31b75210e5.gif)
Sunset (4:25 PM-5:21 PM)

In the original game, the sun basically moves once every 3 game minutes, although sometimes the interval from the last movement is only 2 minutes. Movement generally seems to be a in a repeating pattern of: diagonal, straight, straight.

![early sunrise](https://user-images.githubusercontent.com/19624336/53697975-2c035b00-3e1a-11e9-8269-c712eaf58069.gif)
Sunrise (6:02 AM-6:17 AM)

As an aside, the movement at the very beginning of the sunrise seems like it might follow a slightly different pattern. It was hidden by a cloud in the above recording, and I recorded it again, but it's hard to tell from just this...

The late sunset was also hidden by a cloud so I didn't get a recording of it.

Anyway, I hope this information is useful for you.

**Comment by afritz1** [comment] 2019-03-03 16:32
Oooh, gifs. Gifs are nice. @Carmina16 and I are working through stuff like this right now with star rendering. The sun's direction probably needs to be a function of the player's current latitude.

**Comment by Allofich** [comment] 2019-03-03 16:39
> The sun's direction probably needs to be a function of the player's current latitude.

Is the original game that advanced in its model? I took these in Glenpoint, High Rock.

**Comment by afritz1** [comment] 2019-03-03 16:40
Follow along in our conversation here: https://github.com/afritz1/OpenTESArena/commit/d9e5498769972c3c307e6569a76dafc5aa974883#commitcomment-32514730

**Comment by Allofich** [comment] 2019-03-03 16:50
Looks like a good bit of math going on here, more than probably anyone would expect! Looks pretty complicated but I'll try and take a closer look at that conversation later, thanks. Hopefully those .gifs can be useful for something, even if just as a guide for what the movement should generally look like. It was fun to make them, anyway.

**Comment by afritz1** [comment] 2019-03-15 05:47
On a related topic, I need to confirm whether space objects appear when it's cloudy/rainy/snowy. @Allofich would you be interested in checking that out?

**Comment by Carmina16** [comment] 2019-03-16 01:15
Sun, stars, and moons are not drawn if there is fog or any weather effect.

**Comment by afritz1** [comment] 2019-03-16 14:57
Cool, I can implement that soon then, thanks.

**Comment by afritz1** [comment] 2019-03-17 00:29
The sun's trajectory is now a function of latitude in commit 3b20adec56259ee2ae4f3d44f775d9ff08896898. It doesn't look the exact same as the gifs above, but maybe that's okay? I dunno.

**Comment by Allofich** [comment] 2019-03-17 09:47
Just tried out the latest code, and it's really starting to look good! With the fast timescale that's being used currently, looking up at the rotating stars in the night sky it felt I was in a planetarium or something.

I traveled to Glenpoint, High Rock and watched the sun movement to compare it to what I saw in the original game, and it looked fine except that it was reversed. It was moving to the left rather than the right.

**Comment by afritz1** [comment] 2019-03-17 14:30
It looks even cooler when you change the star count from 40 to 8000 in `DistantSky::init()` 😉. That's what I used to make sure the projection was correct at every point in space. Like I said on Twitter a while ago, distant land and stars are what give the game its "wonder" and make you feel like you're a part of something bigger.

So yeah, I tested it in Glenpoint as well, but in order to have it rotate to the right, it seems like the sun's latitude needs to be changed far more than what @Carmina16 suggested (with the additional 13 Arena angle units). So I'm not sure of the correct way to go about it. And besides, whenever the player's in the southern hemisphere, the sun barely makes it halfway up in the sky, so we can't just "add more" to the sun's latitude.

**Comment by Carmina16** [comment] 2019-03-17 20:20
Make sure you are rotating it -(_latitude_+13) counterclockwise (or _latitude_+13 clockwise).

**Comment by afritz1** [comment] 2019-03-19 15:45
This commit 002b47bfeb413f5b879dc98cb4fe0e50d6c942ab makes the sun's trajectory look a bit better. It goes up and slightly to the right in Glenpoint and up and slightly to the left in Archen Grangrove, Summurset Isle. There is a mountain in the way at Archen Grangrove but I could see where the sun was going after ~7:00am I think.

I think part of the problem was that the effect of latitude on the rotation was too strong. I changed it from Pi/2 to Pi/8 and it looks a lot better. Still not perfect though? Not sure.

**Comment by Carmina16** [comment] 2019-03-20 00:47
The maximum vanilla sun angle should be about 60°. What values do you get?

**Comment by afritz1** [comment] 2019-03-20 04:08
About 20 degrees in Solitude, Skyrim I guess. But if it looks correct, then what? If I don't use Pi/8 in the latitude calculation then the sun appears too close to the horizon at noon in more south places like Summurset Isle and Black Marsh.

**Comment by afritz1** [comment] 2021-03-27 21:41
Recently made some revisions to the sun and moon positions on the chunk system branch (#200). Still not sure if they match the original game but the way the positions are defined now is a lot more convenient.

**Comment by Thunderforge** [comment] 2021-03-30 03:35
@Carmina16 If you get a chance, it would be helpful to see if the positions are any closer to the original game now in the newly released 0.13.0.

**Comment by Thunderforge** [comment] 2021-03-30 03:49
From @afritz1 in Discord:

> The three places I would test with are the Imperial City, Solitude in Skyrim, and Senchal in Elsweyr. The sun is affected by the player's latitude, and those three places have the most distinct latitudes (Imperial City: middle, Solitude: max, Senchal: min).

**Comment by Thunderforge** [comment] 2021-06-24 00:59
In the Discord, Zeri proved that the 0.14.0 behavior is working as intended, as shown in the two videos attached.

https://user-images.githubusercontent.com/6200170/123186291-7088e980-d45d-11eb-8cee-59ae3422e348.mp4

https://user-images.githubusercontent.com/6200170/123186295-71ba1680-d45d-11eb-8d09-ebc2efaa3fec.mp4

Closing this bug as complete.

**Closed by Thunderforge** 2021-06-24 00:59 UTC
Labels: bug
